# Generated by Django 5.1 on 2026-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datakeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorEvaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('platform', models.CharField(default='instagram', max_length=20)),
                ('region', models.CharField(default='us', max_length=10)),
                ('posts_analyzed', models.IntegerField(default=0)),
                ('avg_content_quality', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_creator_fit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_composite_v2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_composite_v2', models.IntegerField(default=0)),
                ('evaluation_tier', models.CharField(blank=True, default='', max_length=5)),
                ('lt_passed', models.BooleanField(blank=True, null=True)),
                ('lt_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ht_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('followers', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category_fit_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('posting_frequency', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('tier1_pass', models.BooleanField(blank=True, null=True)),
                ('tier2_score', models.IntegerField(default=0)),
                ('tier3a_score', models.IntegerField(default=0)),
                ('tier3b_score', models.IntegerField(default=0)),
                ('tier4_score', models.IntegerField(default=0)),
                ('crm_pushed', models.BooleanField(default=False)),
                ('crm_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gk_creator_evaluations',
            },
        ),
        migrations.AddField(
            model_name='contentposts',
            name='composite_v2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='evaluation_tier',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='frame_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='lt_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='media_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='media_stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='media_tier',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='contentposts',
            name='tier_scores_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
